[env]
_.path = [ '{{config_root}}/node_modules/.bin' ]
_.file = { path = ".env", redact = true }

[hooks]
postinstall = "npx corepack enable"

[settings]
experimental = true

[tools]
"npm:@antfu/ni" = "latest"
"ubi:blake-mealey/mantle" = "0.11.18"
"ubi:jacktabscode/asphalt" = "1.2.0"
"ubi:lune-org/lune" = "0.10.4"
"ubi:rojo-rbx/rojo" = "7.6.1"
"ubi:seaofvoices/darklua" = "0.17.3"
node = { version = "lts", postinstall = "corepack enable" }
